#!/bin/bash

set -eu

old=`mktemp`
new=`mktemp`

ls -1 $@ | tee $old > $new

${EDITOR:-vi} $new

[[ `wc -l < $old` -ne `wc -l < $new` ]] && exit -1

paste $old $new | while read line; do
  [[ `cut -f1 <<<$line` != `cut -f2 <<<$line` ]] && mv -iv $line
done

rm -f $old $new
