# Languages

## Binary

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']

## Ruby

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'noprompt/vim-yardoc'
on_ft = 'ruby'
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/vim-yardoc.rc.vim
'''

## HTML

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = 'html'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug', 'vue']

## CSS

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

## JavaScript

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'vue']

## Vue

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

## Elixir

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

## Rust

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

## Haskell

[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = 'haskell'

## JSON

repo = 'elzr/vim-json'
on_ft = 'json'
hook_source = '''
  let g:vim_json_syntax_conceal = 0
'''

## CSV

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft = 'csv'

## TOML

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

## Terraform

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
