# CoC

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'josa42/vim-lightline-coc'
depends = ['lightline.vim', 'coc.nvim']
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/lightline-coc.rc.vim
'''

[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'
depends = ['coc.nvim']

# Plugins

[[plugins]]
repo = 'josa42/coc-sh'
depends = ['coc.nvim']

[[plugins]]
repo = 'clangd/coc-clangd'
depends = ['coc.nvim']

[[plugins]]
repo = 'neoclide/coc-css'
depends = ['coc.nvim']

[[plugins]]
repo = 'neoclide/coc-html'
depends = ['coc.nvim']

[[plugins]]
repo = 'neoclide/coc-tsserver'
depends = ['coc.nvim']

[[plugins]]
repo = 'neoclide/coc-vetur'
depends = ['coc.nvim']

[[plugins]]
repo = 'neoclide/coc-json'
depends = ['coc.nvim']

[[plugins]]
repo = 'josa42/coc-docker'
depends = ['coc.nvim']

[[plugins]]
repo = 'fannheyward/coc-sql'
depends = ['coc.nvim']

[[plugins]]
repo = 'neoclide/coc-solargraph'
depends = ['coc.nvim']
