[[plugins]]
repo = 'Shougo/dein.vim'

# Appearance

[[plugins]]
repo = 'yantene/molokai'
hook_add = 'au cs_hook VimEnter * nested colorscheme molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 'colorscheme': 'wombat' }
'''

# Controll

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  nmap f <plug>(easymotion-overwin-f2)
'''

[[plugins]]
repo = 'tmhedberg/matchit'

# Completion

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<tab>"
'''
# Note: Execute the :UpdateRemotePlugins and restart Neovim.

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev  = 'next'
build = 'bash install.sh'
hook_add = '''
  set hidden
  let g:LanguageClient_serverCommands = {
  \ 'rust': ['rustup', 'run', 'stable', 'rls'],
  \ 'ruby': ['solargraph', 'stdio'],
  \ 'vue': ['vls'],
  \ 'javascript': ['javascript-typescript-stdio'],
  \ 'typescript': ['javascript-typescript-stdio'],
  \}
  let g:LanguageClient_autoStart = 1
  nnoremap <F5>          :call LanguageClient_contextMenu()<CR>
  nnoremap <silent> K    :call LanguageClient#textDocument_hover()<CR>
  nnoremap <silent> gd   :call LanguageClient#textDocument_definition()<CR>
  nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
'''

# Lint

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let b:ale_linters = {
  \  'javascript': ['eslint'],
  \}
'''

# Tools

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
