[[plugins]]
repo = 'Shougo/dein.vim'

# Appearance

[[plugins]]
repo = 'yantene/molokai'
hook_add = 'au cs_hook VimEnter * nested colorscheme molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/lightline.rc.vim
'''

# Controll

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/easymotion.rc.vim
'''

[[plugins]]
repo = 'tmhedberg/matchit'

# Linter

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/lightline-ale.rc.vim
'''

# Language Server Protocol

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
hook_add = '''
source ${XDG_CONFIG_HOME}/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'josa42/vim-lightline-coc'
depends = ['lightline.vim', 'coc.nvim']

# Tools

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
