#!/bin/bash

echo 'Subjects: '

read -p '  C (JP): ' c
[[ -z ${c} ]] && c='JP'
read -p '  ST (Tokyo): ' st
[[ -z ${st} ]] && st='Tokyo'
read -p '  L (Meguro, Meguro-ku): ' l
[[ -z ${l} ]] && l='Meguro, Meguro-ku'
read -p '  O (Example Co., Ltd.): ' o
[[ -z ${o} ]] && o='Example Co., Ltd.'
read -p '  OU (Example Division): ' ou
[[ -z ${ou} ]] && ou='Example Division'
read -p '  CN (example.co.jp): ' dn
[[ -z ${dn} ]] && dn='example.co.jp'
read -p '  Days (365): ' days
[[ -z ${days} ]] && days='365'

echo 'Output path: '

read -p '  csr (./server.csr): ' csr
[[ -z ${csr} ]] && csr='./server.csr'
read -p '  key (./server.key): ' key
[[ -z ${key} ]] && key='./server.key'
read -p '  crt (./server.crt): ' crt
[[ -z ${crt} ]] && crt='./server.crt'


set -eux

openssl req -new -sha256 -newkey rsa:2048 -nodes\
  -out    ${csr}\
  -keyout ${key}\
  -subj   "/C=${c}/ST=${st}/L=${l}/O=${o}/OU=${ou}/CN=${dn}"
openssl x509 -in ${csr} -days ${days} -req -signkey ${key} > ${crt}

set +x
