#!/bin/sh

case $# in
  0)
    ;;
  1)
    case $1 in
      on)
        xrandr --output eDP1 --auto
        xrandr --output HDMI1 --auto
        xrandr --output HDMI1 --left-of eDP1
        xrandr --output HDMI1 --primary
        exit 0;;

      off)
        xrandr --output eDP1 --auto
        xrandr --output HDMI1 --off
        exit 0;;
    esac
    ;;
esac

echo "invalid arguments"
exit 1
