#!/bin/sh

if [ $# -eq 1 ]
then
  case $1 in
    on)
      xrandr --output HDMI1 --auto
      xrandr --output HDMI1 --left-of eDP1
      xrandr --output HDMI1 --primary;;

    off)
      xrandr --output HDMI1 --off;;
  esac
  exit 0
fi

echo "invalid arguments"
exit 1
