#!/bin/ruby
require 'fileutils'

TRASH = '/home/yantene/trash'
time = Time.now.strftime "%s"
ARGV.each do |path|
  files = Dir.glob(path)
  files.each do |file|
    puts "Removing #{file}"
    FileUtils.mkdir_p(TRASH + '/' + time)
    FileUtils.mv(file, TRASH + (TRASH[-1] == '/' ? '' : '/') + time + '/' + File.expand_path(file).gsub('/', '-'))
  end
end

