#!/bin/sh
#vboxmanage startvm "Windows 7"
qemu-system-x86_64\
  -cpu host\
  -m 2048\
  -vga std\
  -usbdevice tablet\
  -localtime\
  -enable-kvm\
  $@\
  /home/yantene/.vmachine/windows/windows.qcow2
